//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPS_Seletiene.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seletieneEntities : DbContext
    {
        public seletieneEntities()
            : base("name=seletieneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<collective> collective { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<qualificationps> qualificationps { get; set; }
        public virtual DbSet<type_ps> type_ps { get; set; }
        public virtual DbSet<user_state> user_state { get; set; }
        public virtual DbSet<userapp> userapp { get; set; }
        public virtual DbSet<ViewProductServices> ViewProductServices { get; set; }
        public virtual DbSet<productservice> productservice { get; set; }
    }
}
