//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPS_Seletiene.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualificationps
    {
        public int id { get; set; }
        public Nullable<int> idproduct { get; set; }
        public string comment { get; set; }
        public int value { get; set; }
        public System.DateTime dateup { get; set; }
    
        public virtual productservice productservice { get; set; }
    }
}
