//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPS_Seletiene.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProductServices
    {
        public int id { get; set; }
        public string name1 { get; set; }
        public string lastname1 { get; set; }
        public string cellphone { get; set; }
        public string email { get; set; }
        public Nullable<int> statususer { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> idcategory { get; set; }
        public Nullable<int> idowner { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime dateup { get; set; }
        public int status { get; set; }
        public string schedule { get; set; }
        public Nullable<double> calification { get; set; }
        public Nullable<int> departmentid { get; set; }
        public int city { get; set; }
        public string imagen { get; set; }
    }
}
